name = "greatwall-us-west"
main = "_worker.js"
compatibility_date = "2026-09-07"
workers_dev = false
preview_urls = false

[[routes]]
pattern = "proxy.woyaoai.online"
custom_domain = true

[placement]
mode = "targeted"
region = "aws:us-west-2"

[[kv_namespaces]]
binding = "KV"
id = "c4160045cd4a4f29ba441725115451f4"

[vars]
HOST = "proxy.woyaoai.online"
